### ISSUE TITLE
Popup layout issues: grey rows extend beyond popup balloon

### ISSUE THREAD

**Issue by zarino** [scraperwiki/map-tool#10]
When text in the popup is of a certain length, the table seems to extend (in this case) 20px beyond the edge of the popup, resulting in weird grey bars.

![screen shot 2013-06-22 at 12 28 41](https://f.cloud.github.com/assets/739624/690742/8f64fdf6-db2f-11e2-96ee-5ad1fd6ffea9.png)

The usual fixes for limiting a table's width don't seem to work:

``` css
.table {
  width: 100%;
  max-width: 100%;
  word-wrap: break-word;
}
```

The cheat's solution would be to set `overflow:hidden` on the table's parent, `.leaflet-popup-content`, but then the cell content collides with the edge of the popup.

![screen shot 2013-06-22 at 12 38 17](https://f.cloud.github.com/assets/739624/690759/8746f08c-db31-11e2-806f-13ac7448963f.png)

I think it's being caused by the truncated link on the second line. Making that shorter fixes the problem.

Another solution, then, might be to remove the RegExp truncation, and instead use:

``` css
.table a {
  display: block;
  width: 80%; /* percentages don't work */
  width: 200px;
  overflow: hidden;
  text-overflow: elipsis;
}
```

But then you're still stuck with the random 200px width, rather than one based on the width of the parent.
